title: @efgm # your name (or website title) here
logo: "/images/logicmonitor headshot egm.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Elena Gonzales Melinger
  <br><br>
  UX Design Research, M.S., Information Studies
  <br><br>
  <a href="https://www.linkedin.com/in/egmelinger/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
